#perpared by Mohamed Ahmed Salama
CC=arm-none-eabi-
CFLAGS=-mcpu=arm926ej-s -g
INCS=-I .
LIBS=
SRC= $(wildcard *.c)
OBJ= $(SRC:.c=.o)
AS= $(wildcard *.s)
ASOBJ=$(AS:.s=.o)

all: learn-in-depth.bin
	
%.o: %.s
	$(CC)as.exe $(CFLAGS) $< -o $@ 2> log
	
%.o: %.c
	$(CC)gcc.exe $(CFLAGS)  -c $(INCS) $< -o $@
	
learn-in-depth.elf: $(OBJ) $(ASOBJ)
	$(CC)ld.exe -T linker_script.ld $(LIBS) $(OBJ) $(ASOBJ) -o $@ -Map=Map_file.map
	
learn-in-depth.bin: learn-in-depth.elf
	$(CC)objcopy.exe -O binary $< $@
	
clean:
	rm -rf *.o *~
	@echo "Everything is clean"
	
	