#perpared by Eng.Mohamed Ahmed Salama (learn-in-depth)
CC=arm-none-eabi-
CFLAGS= -mcpu=cortex-m4 -mthumb -gdwarf-2 -g
INCS=-I .
LIBS=
SRC= $(wildcard *.c)
OBJ= $(SRC:.c=.o)
AS= $(wildcard *.s)
ASOBJ=$(AS:.s=.o)
project_name = Unit3_Lab4_cortexM4
all: $(project_name).bin
	@echo "Build is done"
%.o: %.s
	$(CC)as.exe $(CFLAGS) $< -o $@ 2> log
	
%.o: %.c
	$(CC)gcc.exe $(CFLAGS)  -c $(INCS) $< -o $@
	
$(project_name).elf: $(OBJ) $(ASOBJ)
	$(CC)ld.exe -T linker_script.ld $(LIBS) $(OBJ) $(ASOBJ) -o $@ -Map=Map_file.map
	cp $(project_name).elf $(project_name).axf
	
$(project_name).bin: $(project_name).elf
	$(CC)objcopy.exe -O binary $< $@
	
clean:
	rm -rf *.o *~
	@echo "Everything is clean"
	
	