#perpared by Eng.Mohamed Ahmed Salama (learn-in-depth)
CC=arm-none-eabi-
CFLAGS= -mcpu=cortex-m3 -mthumb -gdwarf-2
INCS=-I .
LIBS=
SRC= $(wildcard *.c)
OBJ= $(SRC:.c=.o)
AS= $(wildcard *.s)
ASOBJ=$(AS:.s=.o)

all: learn-in-depth.hex
	
%.o: %.s
	$(CC)as.exe $(CFLAGS) $< -o $@ 2> log
	
%.o: %.c
	$(CC)gcc.exe $(CFLAGS)  -c $(INCS) $< -o $@
	
learn-in-depth.elf: $(OBJ) $(ASOBJ)
	$(CC)ld.exe -T linker_script.ld $(LIBS) $(OBJ) $(ASOBJ) -o $@ -Map=Map_file.map
	
learn-in-depth.hex: learn-in-depth.elf
	$(CC)objcopy.exe -O binary $< $@
	@echo "Build is done"
clean:
	rm -rf *.o *~
	@echo "Everything is clean"
	
	